# Setup
title:            Divya Godayal
tagline:          'Portfolio'

author:
  name:           'Abinaya Thiyagarajan'
  url:            https://www.linkedin.com/in/abinaya-thiyagarajan/  
  github:         Abinaya Thiyagarajan
  
plugins: 
  - jekyll-paginate
  - jekyll-gist
